# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/klxytx/androidProj/BTCCode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/klxytx/androidProj/BTCCode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/klxytx/androidProj/BTCCode/CMakeFiles /Users/klxytx/androidProj/BTCCode/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/klxytx/androidProj/BTCCode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named torrent

# Build rule for target.
torrent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 torrent
.PHONY : torrent

# fast build rule for target.
torrent/fast:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/build
.PHONY : torrent/fast

bitfield.o: bitfield.c.o

.PHONY : bitfield.o

# target to build an object file
bitfield.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/bitfield.c.o
.PHONY : bitfield.c.o

bitfield.i: bitfield.c.i

.PHONY : bitfield.i

# target to preprocess a source file
bitfield.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/bitfield.c.i
.PHONY : bitfield.c.i

bitfield.s: bitfield.c.s

.PHONY : bitfield.s

# target to generate assembly for a file
bitfield.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/bitfield.c.s
.PHONY : bitfield.c.s

bterror.o: bterror.c.o

.PHONY : bterror.o

# target to build an object file
bterror.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/bterror.c.o
.PHONY : bterror.c.o

bterror.i: bterror.c.i

.PHONY : bterror.i

# target to preprocess a source file
bterror.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/bterror.c.i
.PHONY : bterror.c.i

bterror.s: bterror.c.s

.PHONY : bterror.s

# target to generate assembly for a file
bterror.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/bterror.c.s
.PHONY : bterror.c.s

data.o: data.c.o

.PHONY : data.o

# target to build an object file
data.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/data.c.o
.PHONY : data.c.o

data.i: data.c.i

.PHONY : data.i

# target to preprocess a source file
data.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/data.c.i
.PHONY : data.c.i

data.s: data.c.s

.PHONY : data.s

# target to generate assembly for a file
data.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/data.c.s
.PHONY : data.c.s

log.o: log.c.o

.PHONY : log.o

# target to build an object file
log.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/log.c.o
.PHONY : log.c.o

log.i: log.c.i

.PHONY : log.i

# target to preprocess a source file
log.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/log.c.i
.PHONY : log.c.i

log.s: log.c.s

.PHONY : log.s

# target to generate assembly for a file
log.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/log.c.s
.PHONY : log.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/main.c.s
.PHONY : main.c.s

message.o: message.c.o

.PHONY : message.o

# target to build an object file
message.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/message.c.o
.PHONY : message.c.o

message.i: message.c.i

.PHONY : message.i

# target to preprocess a source file
message.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/message.c.i
.PHONY : message.c.i

message.s: message.c.s

.PHONY : message.s

# target to generate assembly for a file
message.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/message.c.s
.PHONY : message.c.s

parse_metafile.o: parse_metafile.c.o

.PHONY : parse_metafile.o

# target to build an object file
parse_metafile.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/parse_metafile.c.o
.PHONY : parse_metafile.c.o

parse_metafile.i: parse_metafile.c.i

.PHONY : parse_metafile.i

# target to preprocess a source file
parse_metafile.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/parse_metafile.c.i
.PHONY : parse_metafile.c.i

parse_metafile.s: parse_metafile.c.s

.PHONY : parse_metafile.s

# target to generate assembly for a file
parse_metafile.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/parse_metafile.c.s
.PHONY : parse_metafile.c.s

peer.o: peer.c.o

.PHONY : peer.o

# target to build an object file
peer.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/peer.c.o
.PHONY : peer.c.o

peer.i: peer.c.i

.PHONY : peer.i

# target to preprocess a source file
peer.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/peer.c.i
.PHONY : peer.c.i

peer.s: peer.c.s

.PHONY : peer.s

# target to generate assembly for a file
peer.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/peer.c.s
.PHONY : peer.c.s

policy.o: policy.c.o

.PHONY : policy.o

# target to build an object file
policy.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/policy.c.o
.PHONY : policy.c.o

policy.i: policy.c.i

.PHONY : policy.i

# target to preprocess a source file
policy.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/policy.c.i
.PHONY : policy.c.i

policy.s: policy.c.s

.PHONY : policy.s

# target to generate assembly for a file
policy.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/policy.c.s
.PHONY : policy.c.s

sha1.o: sha1.c.o

.PHONY : sha1.o

# target to build an object file
sha1.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/sha1.c.o
.PHONY : sha1.c.o

sha1.i: sha1.c.i

.PHONY : sha1.i

# target to preprocess a source file
sha1.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/sha1.c.i
.PHONY : sha1.c.i

sha1.s: sha1.c.s

.PHONY : sha1.s

# target to generate assembly for a file
sha1.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/sha1.c.s
.PHONY : sha1.c.s

signal_hander.o: signal_hander.c.o

.PHONY : signal_hander.o

# target to build an object file
signal_hander.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/signal_hander.c.o
.PHONY : signal_hander.c.o

signal_hander.i: signal_hander.c.i

.PHONY : signal_hander.i

# target to preprocess a source file
signal_hander.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/signal_hander.c.i
.PHONY : signal_hander.c.i

signal_hander.s: signal_hander.c.s

.PHONY : signal_hander.s

# target to generate assembly for a file
signal_hander.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/signal_hander.c.s
.PHONY : signal_hander.c.s

torrent.o: torrent.c.o

.PHONY : torrent.o

# target to build an object file
torrent.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/torrent.c.o
.PHONY : torrent.c.o

torrent.i: torrent.c.i

.PHONY : torrent.i

# target to preprocess a source file
torrent.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/torrent.c.i
.PHONY : torrent.c.i

torrent.s: torrent.c.s

.PHONY : torrent.s

# target to generate assembly for a file
torrent.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/torrent.c.s
.PHONY : torrent.c.s

tracker.o: tracker.c.o

.PHONY : tracker.o

# target to build an object file
tracker.c.o:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/tracker.c.o
.PHONY : tracker.c.o

tracker.i: tracker.c.i

.PHONY : tracker.i

# target to preprocess a source file
tracker.c.i:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/tracker.c.i
.PHONY : tracker.c.i

tracker.s: tracker.c.s

.PHONY : tracker.s

# target to generate assembly for a file
tracker.c.s:
	$(MAKE) -f CMakeFiles/torrent.dir/build.make CMakeFiles/torrent.dir/tracker.c.s
.PHONY : tracker.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... torrent"
	@echo "... bitfield.o"
	@echo "... bitfield.i"
	@echo "... bitfield.s"
	@echo "... bterror.o"
	@echo "... bterror.i"
	@echo "... bterror.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... message.o"
	@echo "... message.i"
	@echo "... message.s"
	@echo "... parse_metafile.o"
	@echo "... parse_metafile.i"
	@echo "... parse_metafile.s"
	@echo "... peer.o"
	@echo "... peer.i"
	@echo "... peer.s"
	@echo "... policy.o"
	@echo "... policy.i"
	@echo "... policy.s"
	@echo "... sha1.o"
	@echo "... sha1.i"
	@echo "... sha1.s"
	@echo "... signal_hander.o"
	@echo "... signal_hander.i"
	@echo "... signal_hander.s"
	@echo "... torrent.o"
	@echo "... torrent.i"
	@echo "... torrent.s"
	@echo "... tracker.o"
	@echo "... tracker.i"
	@echo "... tracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

